<#
.SYNOPSIS
Generates local MCP client configuration for Codex, VS Code MCP, and generic MCP clients.

.DESCRIPTION
This script writes:
  .codex/config.toml
  .vscode/mcp.json
  .mcp.json

It defaults to the current repo root and configures MCPServer to expose Ollama-backed
local inference tools using qwen3-coder:30b at 128K context.
#>
[CmdletBinding()]
param(
    [string] $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path,
    [string] $DefaultModel = 'qwen3-coder:30b',
    [string[]] $AllowedModels = @('qwen3-coder:30b', 'qwen2.5-coder:14b', 'devstral-small-2'),
    [string] $OllamaBaseUrl = 'http://127.0.0.1:11434',
    [int] $ContextLength = 131072,
    [int] $NumPredict = 32000,
    [int] $MaxPromptChars = 500000,
    [int] $MaxOutputChars = 32000,
    [int] $ToolTimeoutSeconds = 900,
    [switch] $Build
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoRoot = [System.IO.Path]::GetFullPath($RepoRoot)
$HostProject = Join-Path $RepoRoot 'src\McpServer.Host\McpServer.Host.csproj'
$HostExe = Join-Path $RepoRoot 'src\McpServer.Host\bin\Release\net10.0\McpServer.Host.exe'
$LogsPath = Join-Path $RepoRoot 'logs'

if ($Build) {
    dotnet build (Join-Path $RepoRoot 'McpServer.slnx') -c Release -v minimal
    if ($LASTEXITCODE -ne 0) {
        throw "dotnet build failed with exit code $LASTEXITCODE."
    }
}

if (-not (Test-Path $HostExe)) {
    Write-Warning "Host executable was not found at '$HostExe'. Run: dotnet build `"$HostProject`" -c Release"
}

New-Item -ItemType Directory -Force -Path (Join-Path $RepoRoot '.codex') | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $RepoRoot '.vscode') | Out-Null
New-Item -ItemType Directory -Force -Path $LogsPath | Out-Null

$env = [ordered]@{
    'ASPNETCORE_ENVIRONMENT' = 'Development'
    'MCPSERVER__WORKSPACE__ROOTPATH' = $RepoRoot
    'MCPSERVER__WORKSPACE__ALLOWEDROOTS__0' = $RepoRoot
    'MCPSERVER__WORKSPACE__ALLOWRUNTIMEWORKSPACEOPEN' = 'true'

    'MCPSERVER__SHELL__ENABLED' = 'true'
    'MCPSERVER__SHELL__ALLOWEDSHELLFALLBACK' = 'false'
    'MCPSERVER__SHELL__ALLOWWINDOWSCOMPATIBILITYSHELL' = 'false'
    'MCPSERVER__SHELL__ALLOWEDCOMMANDS__0' = 'dotnet'
    'MCPSERVER__SHELL__ALLOWEDCOMMANDS__1' = 'git'
    'MCPSERVER__SHELL__MAXTIMEOUTSECONDS' = '300'
    'MCPSERVER__SHELL__MAXOUTPUTCHARS' = '200000'

    'MCPSERVER__WEBACCESS__ENABLED' = 'false'
    'MCPSERVER__SSH__ENABLED' = 'false'

    'MCPSERVER__OLLAMA__ENABLED' = 'true'
    'MCPSERVER__OLLAMA__BASEURL' = $OllamaBaseUrl
    'MCPSERVER__OLLAMA__DEFAULTMODEL' = $DefaultModel
    'MCPSERVER__OLLAMA__TIMEOUTSECONDS' = '240'
    'MCPSERVER__OLLAMA__MAXTIMEOUTSECONDS' = [string]$ToolTimeoutSeconds
    'MCPSERVER__OLLAMA__MAXPROMPTCHARS' = [string]$MaxPromptChars
    'MCPSERVER__OLLAMA__MAXOUTPUTCHARS' = [string]$MaxOutputChars
    'MCPSERVER__OLLAMA__CONTEXTLENGTH' = [string]$ContextLength
    'MCPSERVER__OLLAMA__NUMPREDICT' = [string]$NumPredict
    'MCPSERVER__OLLAMA__TEMPERATURE' = '0.15'
    'MCPSERVER__OLLAMA__ALLOWNONLOOPBACKBASEURL' = 'false'

    'MCPSERVER_LOG_DIRECTORY' = $LogsPath
}

for ($i = 0; $i -lt $AllowedModels.Count; $i++) {
    $env["MCPSERVER__OLLAMA__ALLOWEDMODELS__$i"] = $AllowedModels[$i]
}

function ConvertTo-TomlLiteral {
    param([string] $Value)
    return "'" + ($Value -replace "'", "''") + "'"
}

$disabledTools = @(
    'fs.delete_path',
    'ssh.execute',
    'web.fetch_url',
    'web.search',
    'web.scrape_url'
)

$codexLines = New-Object System.Collections.Generic.List[string]
$codexLines.Add('# Generated by scripts/Install-LocalMcpClients.ps1')
$codexLines.Add('# Repo-local Codex MCP configuration for MCPServer.')
$codexLines.Add('')
$codexLines.Add('[mcp_servers.mcpserver]')
$codexLines.Add('command = ' + (ConvertTo-TomlLiteral $HostExe))
$codexLines.Add('args = []')
$codexLines.Add('cwd = ' + (ConvertTo-TomlLiteral $RepoRoot))
$codexLines.Add('startup_timeout_sec = 30')
$codexLines.Add('tool_timeout_sec = ' + $ToolTimeoutSeconds)
$codexLines.Add('enabled = true')
$codexLines.Add('required = true')
$codexLines.Add('disabled_tools = [')
foreach ($tool in $disabledTools) {
    $codexLines.Add('  ' + (ConvertTo-TomlLiteral $tool) + ',')
}
$codexLines.Add(']')
$codexLines.Add('')
$codexLines.Add('[mcp_servers.mcpserver.env]')
foreach ($entry in $env.GetEnumerator()) {
    $codexLines.Add($entry.Key + ' = ' + (ConvertTo-TomlLiteral ([string]$entry.Value)))
}

Set-Content -Path (Join-Path $RepoRoot '.codex\config.toml') -Value $codexLines -Encoding UTF8

$server = [ordered]@{
    type = 'stdio'
    command = $HostExe
    args = @()
    cwd = $RepoRoot
    env = $env
}

$vscodeConfig = [ordered]@{
    servers = [ordered]@{
        mcpserver = $server
    }
}

$mcpConfig = [ordered]@{
    inputs = @()
    servers = [ordered]@{
        mcpserver = $server
    }
}

$vscodeConfig | ConvertTo-Json -Depth 20 | Set-Content -Path (Join-Path $RepoRoot '.vscode\mcp.json') -Encoding UTF8
$mcpConfig | ConvertTo-Json -Depth 20 | Set-Content -Path (Join-Path $RepoRoot '.mcp.json') -Encoding UTF8

Write-Host "Generated Codex config:  $((Join-Path $RepoRoot '.codex\config.toml'))"
Write-Host "Generated VS Code MCP:  $((Join-Path $RepoRoot '.vscode\mcp.json'))"
Write-Host "Generated generic MCP: $((Join-Path $RepoRoot '.mcp.json'))"
Write-Host "Default local model:   $DefaultModel"
Write-Host "Context length:        $ContextLength"
